# Generated by Django 5.1.2 on 2024-11-08 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('offer', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product_offers',
            name='product_id',
        ),
        migrations.DeleteModel(
            name='Brand_Offers',
        ),
        migrations.DeleteModel(
            name='Product_Offers',
        ),
    ]
