# Generated by Django 5.1.2 on 2024-11-08 10:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offer', '0003_initial'),
        ('products', '0024_alter_productdetails_image2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_offers',
            name='product_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.productdetails'),
        ),
    ]
