# Generated by Django 5.1.2 on 2024-11-08 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('offer', '0004_alter_product_offers_product_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='brand_offers',
            old_name='strted_date',
            new_name='started_date',
        ),
        migrations.RenameField(
            model_name='product_offers',
            old_name='strted_date',
            new_name='started_date',
        ),
    ]
