# Generated by Django 5.1.2 on 2024-11-08 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offer', '0005_rename_strted_date_brand_offers_started_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand_offers',
            name='offer_price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='product_offers',
            name='offer_price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
