# Generated by Django 5.1.2 on 2024-11-09 05:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('offer', '0006_alter_brand_offers_offer_price_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='brand_offers',
            old_name='brand_id',
            new_name='brand',
        ),
        migrations.RenameField(
            model_name='product_offers',
            old_name='product_id',
            new_name='product',
        ),
    ]
