# Generated by Django 5.1.2 on 2025-03-22 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offer', '0008_alter_brand_offers_end_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand_offers',
            name='offer_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='product_offers',
            name='offer_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
