# Generated by Django 5.1.2 on 2024-11-05 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coupon', '0002_rename_min_order_amount_coupon_min_purchase_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='couponuser',
            name='coupon',
        ),
        migrations.RemoveField(
            model_name='couponuser',
            name='user',
        ),
        migrations.DeleteModel(
            name='Coupon',
        ),
        migrations.DeleteModel(
            name='CouponUser',
        ),
    ]
