# Generated by Django 5.1.2 on 2024-11-07 04:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coupon', '0004_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CouponUser',
        ),
    ]
