# Generated by Django 5.1.2 on 2024-11-07 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupon', '0006_couponuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='category',
            field=models.CharField(default='None', max_length=30, null=True),
        ),
    ]
