# Generated by Django 5.1.2 on 2024-11-09 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupon', '0007_coupon_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='usage_limit',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
