# Generated by Django 5.1.2 on 2024-11-11 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0006_alter_order_coupon_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='total_offer_discount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
