# Generated by Django 5.1.2 on 2024-10-27 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='country',
            new_name='district',
        ),
    ]
