# Generated by Django 5.1.2 on 2024-10-24 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_brand_is_deleted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='is_deleted',
            field=models.BooleanField(default=True),
        ),
    ]
