# Generated by Django 5.1.2 on 2024-10-26 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_productdetails_variantsize'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variantsize',
            name='size',
            field=models.CharField(max_length=10),
        ),
    ]
