# Generated by Django 5.1.2 on 2024-10-26 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0015_alter_variantsize_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variantsize',
            name='price',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
