# Generated by Django 5.1.2 on 2024-10-26 16:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0016_alter_variantsize_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variantsize',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='products.productdetails'),
        ),
    ]
