# Generated by Django 5.1.2 on 2024-10-27 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0017_alter_variantsize_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productdetails',
            name='is_deleted',
            field=models.BooleanField(default=True),
        ),
    ]
