# Generated by Django 5.1.2 on 2024-10-27 06:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0018_alter_productdetails_is_deleted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='variant',
            name='product',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
        migrations.DeleteModel(
            name='Variant',
        ),
    ]
