# Generated by Django 5.1.2 on 2024-10-31 04:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0019_remove_variant_product_delete_product_delete_variant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productdetails',
            name='brand',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='products.brand'),
        ),
    ]
