# Generated by Django 5.1.2 on 2024-11-01 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0020_alter_productdetails_brand'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variantsize',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
