# Generated by Django 5.1.2 on 2024-11-09 04:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0025_productdetails_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productdetails',
            name='price',
        ),
    ]
