# Generated by Django 5.1.2 on 2024-11-09 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0027_productdetails_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='variantsize',
            name='price',
        ),
    ]
