# Generated by Django 5.1.2 on 2024-11-10 19:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0029_alter_variantsize_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='variantsize',
            options={'ordering': ['-size']},
        ),
    ]
