# Generated by Django 5.1.2 on 2024-11-19 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0030_alter_variantsize_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='variantsize',
            options={'ordering': ['size']},
        ),
    ]
