# Generated by Django 5.1.2 on 2024-11-10 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='Dtails',
            new_name='Details',
        ),
    ]
