# Generated by Django 5.1.2 on 2024-11-10 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0002_rename_dtails_transaction_details'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='Details',
            new_name='details',
        ),
    ]
