# Generated by Django 5.1.2 on 2024-11-10 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0003_rename_details_transaction_details'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='details',
            field=models.CharField(max_length=256),
        ),
    ]
