# Generated by Django 5.1.2 on 2024-10-23 18:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_users_options_alter_users_managers_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='users',
            old_name='user_id',
            new_name='userid',
        ),
    ]
