# Generated by Django 5.1.2 on 2024-10-27 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_remove_users_created_at_remove_users_isblocked'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='address',
        ),
    ]
