# Generated by Django 5.1.2 on 2024-11-06 04:00

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_remove_users_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='profile',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
    ]
